from PyQt5 import QtCore, QtGui, QtWidgets

class Informacion(object):
    def setupUi(self, Form2):
        Form2.setObjectName("Form2")
        Form2.resize(719, 425)
        Form2.setStyleSheet("background-color: rgb(45, 109, 49);")
        self.centralwidget = QtWidgets.QWidget(Form2)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 20, 651, 24))
        self.label.setStyleSheet("font: 87 12pt \"Arial Black\";\ncolor: rgb(0, 0, 127);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 60, 651, 24))
        self.label_2.setStyleSheet("font: 87 12pt \"Arial Black\";\ncolor: rgb(0, 0, 127);")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 100, 651, 24))
        self.label_3.setStyleSheet("font: 87 12pt \"Arial Black\";\ncolor: rgb(0, 0, 127);")
        self.label_3.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(30, 140, 651, 24))
        self.label_4.setStyleSheet("font: 87 12pt \"Arial Black\";\ncolor: rgb(0, 0, 127);")
        self.label_4.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(30, 180, 651, 24))
        self.label_5.setStyleSheet("font: 87 12pt \"Arial Black\";\ncolor: rgb(0, 0, 127);")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(30, 220, 651, 24))
        self.label_6.setStyleSheet("font: 87 12pt \"Arial Black\";\ncolor: rgb(255, 255, 0);")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(30, 260, 651, 24))
        self.label_7.setStyleSheet("font: 87 12pt \"Arial Black\";\ncolor: rgb(255, 255, 0);")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(30, 300, 651, 24))
        self.label_8.setStyleSheet("font: 87 12pt \"Arial Black\";\ncolor: rgb(255, 255, 0);")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(30, 340, 651, 24))
        self.label_9.setStyleSheet("font: 87 12pt \"Arial Black\";\ncolor: rgb(255, 255, 0);")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(30, 380, 651, 24))
        self.label_10.setStyleSheet("font: 87 12pt \"Arial Black\";\ncolor: rgb(255, 255, 0);")
        self.label_10.setObjectName("label_10")
        self.statusbar = QtWidgets.QStatusBar(Form2)
        self.statusbar.setObjectName("statusbar")

        self.retranslateUi(Form2)
        QtCore.QMetaObject.connectSlotsByName(Form2)
    
    def retranslateUi(self, Form2):
        _translate = QtCore.QCoreApplication.translate
        Form2.setWindowTitle(_translate("Form2", "Informacion Estudiante"))
        self.label.setText(_translate("Form2", "Ronaldo Javier Posadas Guerra"))
        self.label_2.setText(_translate("Form2", "202004770"))
        self.label_3.setText(_translate("Form2", "Introduccion a la Programacion y Computacion 2 Seccion A"))
        self.label_4.setText(_translate("Form2", "Ingenieria en Ciencias y Sistemas"))
        self.label_5.setText(_translate("Form2", "4to Semestre"))
        self.label_6.setText(_translate("Form2", "Python 3.9.2"))
        self.label_7.setText(_translate("Form2", "Libreria PyQt"))
        self.label_8.setText(_translate("Form2", "Libreria xml.etree.ElementTree"))
        self.label_9.setText(_translate("Form2", "Graphviz 2.49.0"))
        self.label_10.setText(_translate("Form2", "Fecha de Lanzamiento 25/09/2021"))